# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('interval', models.DurationField()),
                ('units', models.CharField(choices=[('ME', 'Unités métriques'), ('US', 'Unités US')], max_length=2)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity', models.PositiveSmallIntegerField()),
                ('dewpoint', models.DecimalField(decimal_places=2, max_digits=4)),
                ('windchill', models.DecimalField(decimal_places=2, max_digits=4)),
                ('heatindex', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=5)),
                ('wind_direction', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_gust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_gust_dir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_2min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_10min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uv_radiation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('solar_radiation', models.PositiveSmallIntegerField()),
                ('et', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(choices=[('IN', 'Institutionnel'), ('OR', 'Association'), ('CO', 'Société'), ('PR', 'Privé')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reading_type', models.CharField(choices=[('MAN', 'Instrument manuel'), ('AUT', 'Instrument automatique')], max_length=3)),
                ('sensor_type', models.CharField(choices=[('ANM', 'Anémomètre'), ('PLG', 'Pluviographe / Pluviomètre'), ('THM', 'Thermomètre'), ('HYM', 'Hygromètre'), ('THH', 'Thermomètre & Hygromètre'), ('PYM', 'Pyranomètre'), ('UVS', 'Capteur UV')], max_length=3)),
                ('precision', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('sensor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.InstrumentModel')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.PositiveIntegerField()),
                ('town', models.CharField(max_length=30)),
                ('gps_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.TextField()),
                ('auto_transmit', models.BooleanField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Network')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Entity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Site')),
            ],
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('station_type', models.CharField(choices=[('RE', 'Lecture directe'), ('TP', 'Station auto (Enregistreurs à bande)'), ('DR', 'Station auto (Enregistreurs numériques)'), ('OT', 'Autre type de station')], max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Brand')),
                ('instruments', models.ManyToManyField(to='weather_collection.InstrumentModel')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='station_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.StationModel'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Station'),
        ),
        migrations.AddField(
            model_name='archive',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Site'),
        ),
        migrations.AddField(
            model_name='archive',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_collection.Station'),
        ),
    ]
